name = "kevinten-api-preview"
main = "src/index.ts"
compatibility_date = "2024-06-20"
workers_dev = true

[vars]
AUTH0_DOMAIN = "dev-8abkwbejxgjbcz1l.us.auth0.com"
AUTH0_AUDIENCE = "https://kevinten-preview/api"
ADMIN_EMAILS = "wshten@gmail.com"
SITE_ORIGIN = "http://localhost:8788"
ALLOWED_ORIGINS = "https://kevinten-interactive-preview.pages.dev,https://kevinten.com,https://www.kevinten.com"

[[d1_databases]]
binding = "DB"
database_name = "kevinten_site_preview"
database_id = "ad0a9263-ea1c-40ab-85e3-902f38e29ccd"

[[kv_namespaces]]
binding = "SITE_KV"
id = "35e9b55b48ce4e5ab3e024e9ee45652e"
preview_id = "ed35ac6db9ea45d4a50b4e6bd1b48fec"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "kevinten-site-preview-assets"

[[queues.producers]]
binding = "EVENTS_QUEUE"
queue = "kevintenpreviewevents"

[[queues.consumers]]
queue = "kevintenpreviewevents"
max_batch_size = 10
max_batch_timeout = 5
